/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright 2011 OpenConcerto, by ILM Informatique. All rights reserved.
 * 
 * The contents of this file are subject to the terms of the GNU General Public License Version 3
 * only ("GPL"). You may not use this file except in compliance with the License. You can obtain a
 * copy of the License at http://www.gnu.org/licenses/gpl-3.0.html See the License for the specific
 * language governing permissions and limitations under the License.
 * 
 * When distributing the software, include this License Header Notice in each file.
 */
 
 package org.openconcerto.sql.utils;

import java.io.File;
import java.io.IOException;

import org.jdom.Document;
import org.jdom.JDOMException;

public class MySQL2Derby extends MySQLXML2 {

    /**
     * Takes a xml dump of the structure of a MySQL base (mysqldump --no-data --xml) and output
     * corresponding sql for Derby.
     * 
     * @param args the path of the xml file.
     * @throws JDOMException if the xml is not valid.
     * @throws IOException if the file can't be read.
     */
    public static void main(String[] args) throws JDOMException, IOException {
        final File xmlFile = new File(args[0]);
        new MySQL2Derby().convert(xmlFile);
    }

    protected void fixXML(Document doc) throws JDOMException {
        super.fixXML(doc);
        fixType(doc, "starts-with", "tinyint(", "smallint");
        fixType(doc, "starts-with", "text", "long varchar");
        fixAutoIncrement(doc);
    }

    protected boolean wantIndexes() {
        return true;
    }

    private void fixAutoIncrement(final Document doc) throws JDOMException {
        fixAttr(doc, "Extra", "contains", "auto_increment", "generated by default as identity");
    }
}
